name: CI
on: [push]

jobs:
  repos-upto-date:
    name: Check .repos are up to date
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Check regenerated are the same
      run: |
        bash template-to-repos.sh
        git diff --quiet *.repo

  centos-installs:
    name: Test CentOS 7 installs
    runs-on: ubuntu-latest
    container: centos:${{ matrix.centos-version }}
    strategy:
      matrix:
        centos-version:
        - 7
        - 7.1.1503
        - 7.2.1511
        - 7.3.1611
        - 7.4.1708
        - 7.5.1804
        - 7.6.1810
        - 7.7.1908

    steps:
    - name: Report CentOS version
      run: |
        cat /etc/centos-release
        echo "CENTOS_RELEASE=${CENTOS_RELEASE:-$(grep -oP '[\d\.]+' /etc/centos-release)}"

    - name: Fail install devtoolset-3 without vault
      run: |
        yum install -y centos-release-scl
        yum install -y devtoolset-3 && exit 1 || exit 0

    - name: Install devtoolset-3 with vault
      run: |
        yum install -y centos-release-scl
        curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/activate.sh | SCL_TAR_SHA=${{ github.sha}} bash
        yum install -y --skip-broken devtoolset-3
